import { Component } from '@angular/core';

@Component({
  selector: 'app-tab3',
  templateUrl: 'tab3.page.html',
  styleUrls: ['tab3.page.scss']
})
export class Tab3Page {
  detail: any = {
    cat: 'Report For Month Of February',
    type: 'New',
    date: '12:00PM',
    req_id: '122',
    remark: 'Generated By Nikhil'
  };
  comment: any = [{
    name: 'Kata',
    status: 'Resolved',
    date: '100',
    bg: '#B0CCBB',
  },{
    name: 'Kumite',
    status: 'Resolved',
    date: '90',
    bg: '#EFFCFA',
  },{
    name: 'Kihion',
    status: 'Resolved',
    date: '45',
    bg: '#B0CCBB',
  }];

  title : any;
  series:any=[];
  chart : any;

  constructor() {}
  ngOnInit() {
    this.chart1();
    
  }


  chart1() : void{
    this.title = {
      text : 'Attendence',
    };
    this.series =[{
      name : 'Present',
      data : [10,20,12,11,10,20,12,11]
    }];
    this.chart = {
      type : 'line'
    };

  }
}
